#!/usr/bin/env bash

mcd () {
    mkdir -p "$1"
    cd "$1"
}

# -----------------------------------------

CURRENT_PATH="$(pwd)"

macro() {
    CURRENT_PATH="$(pwd)"
}

polo() {
    cd "$CURRENT_PATH" || exit
}

# -----------------------------------------

