#!/usr/bin/env bash

hello () {
    # https://github.com/notes-lpj/cowsay-words
    fortune -s | cowsay
}

# -----------------------------------------

mcd () {
    mkdir -p "$1"
    cd "$1"
}

# -----------------------------------------

CURRENT_PATH="$(pwd)"

macro() {
    CURRENT_PATH="$(pwd)"
}

polo() {
    cd "$CURRENT_PATH" || exit
}

# -----------------------------------------

