
[opener]
edit = [
	{ run = '${EDITOR:-vim} "$@"', block = true, for = "unix" },
]
play_video = [
	{ run = '/Applications/VLC.app/Contents/MacOS/VLC "$@"', orphan = true, for = "unix" },
]
play_audio = [
	{ run = 'play "$@"', for = "unix" },
]
open = [
	{ run = 'open "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
	# Markdown
	{ name = "*.md",  use = [ "edit" ] },
	# Media
	{ name = "*.mp4",  use = [ "play_video" ] },
	{ name = "*.mp3",  use = [ "play_audio" ] },
	# Text
	{ mime = "text/*",  use = [ "edit" ] },
	# Fallback
	{ name = "*", use = [ "open" ] },
]

[manager]
linemode = "permissions"

[preview]
max_width = 9999999
max_hight = 9999999

